### PR TITLE
hip-xxxx: "thumb wrestle" hard fork

### PR DESCRIPTION
**Pull request by pinheadmz**
This doc is a draft WIP as well as the experimental implementation: https://github.com/pinheadmz/hsd/commits/thumbwrestle-1

Both the English and the JavaScript need more testing and cleanup, but I think it's ready enough for discussion to post on github.

### CODE REVIEW

**Comment by befranz** [comment]
I propose to extend the claim period of ALL reserved names for at least another four years.

The group of the Top100k names (flag none, currently including 503.xx HNS) contains many low-value domains no longer actively in use but also a lot of well-known domestic and international brands and companies.

Using those Handshake TLDs by others than the legal rights holders will create confusion with the users and predetermined conflicts with the brand/name owners. In the end it’s just bad reputation for Handshake. So giving those companies more time is for sure a good decision for Handshake.

I made an [extract out of the Top100k names (flag none)](https://gist.github.com/befranz/873c915860a540ea399c1deecf4235db) with the Top20 domains from about 50 ccTLDs since most domestic brands/companies use ccTLDs of/for their markets. The Top200 .com domains from this group are also included.

I assume that many of them are somehow protected. It’s definitely so for some domains with European ccTLDs I know. The same goes for all the international brands and well known companies which are not even in this extract.

I propose to eliminate the financial incentive for this name group, so that only those will claim who are really interested in their name on Handshake. Something like 10 HNS instead of currently 503 HNS should be enough to register and probably renew their name a few times in the future.

**Comment by Falci** [comment]
Assigning `HIP-0014`

**Comment by DIPMR** [comment]
I agree with @befranz.
If we are extending name claims then extend it for another 4 years but reduce the HNS coins associated with the claim as we know for sure most of the claims are not from the originally assigned domain owners. 
And if possible release the names in staggered manner over a period of time.

**Comment by pinheadmz** [comment]
Im going to merge this as-is as hip-0014. @befranz please open a PR to update hip-0014 with your precise protocol change-changes. I think that should be the worflow, then the community can comment on each propsed poroposal change.

**Comment by nickorlabs** [comment]
Curious if 
a. @befranz had a chance to "open a PR to update hip-0014 with your precise protocol change-changes."

b. how far this is from complete?  @pinheadmz you are a wizard so you could have already finished it and we just need testing?

**Pull request merged**
